/** Simple Icons CDN slug per technology — https://cdn.simpleicons.org/{slug} */
export const techIconSlugs: Record<string, string> = {
  Angular: "angular",
  "Next.js": "nextdotjs",
  React: "react",
  Remix: "remix",
  Svelte: "svelte",
  "Vue.js": "vuedotjs",
  Expo: "expo",
  Flutter: "flutter",
  "React Native": "react",
  JavaScript: "javascript",
  PHP: "php",
  Python: "python",
  TypeScript: "typescript",
  Django: "django",
  "Express.js": "express",
  FastAPI: "fastapi",
  Laravel: "laravel",
  NestJS: "nestjs",
  "Node.js": "nodedotjs",
  Firebase: "firebase",
  MongoDB: "mongodb",
  MySQL: "mysql",
  PostgreSQL: "postgresql",
  Prisma: "prisma",
  Redis: "redis",
  Supabase: "supabase",
  GraphQL: "graphql",
  "REST API": "openapiinitiative",
  tRPC: "trpc",
  WebSockets: "socketdotio",
  Bootstrap: "bootstrap",
  CSS3: "css",
  "Material UI": "mui",
  Sass: "sass",
  "Shadcn UI": "shadcnui",
  "Tailwind CSS": "tailwindcss",
  "Framer Motion": "framer",
  GSAP: "greensock",
  Lottie: "lottiefiles",
  AWS: "amazonaws",
  Azure: "azure",
  Cloudflare: "cloudflare",
  DigitalOcean: "digitalocean",
  "Google Cloud": "googlecloud",
  Vercel: "vercel",
  Docker: "docker",
  "GitHub Actions": "githubactions",
  "GitLab CI": "gitlab",
  Kubernetes: "kubernetes",
  Nginx: "nginx",
  PM2: "pm2",
  "Claude API": "anthropic",
  "Gemini API": "google",
  LangChain: "langchain",
  "OpenAI API": "openai",
  TensorFlow: "tensorflow",
  Shopify: "shopify",
  Strapi: "strapi",
  WooCommerce: "woocommerce",
  WordPress: "wordpress",
  Cypress: "cypress",
  ESLint: "eslint",
  Figma: "figma",
  Git: "git",
  Jest: "jest",
  Playwright: "playwright",
  Postman: "postman",
  Vite: "vite",
  Webpack: "webpack",
  Nodemailer: "nodemailer",
  Razorpay: "razorpay",
  Stripe: "stripe",
  Twilio: "twilio",
  "WhatsApp API": "whatsapp",
};

export function getTechIconUrl(name: string, color = "38bdf8") {
  const slug = techIconSlugs[name];
  if (!slug) return null;
  return `https://cdn.simpleicons.org/${slug}/${color}`;
}
